In [1]:
import os
import pandas as pd
from pydantic import TypeAdapter

In [4]:
data = pd.read_csv('../../data/original/demonstration_data.csv', sep = ';')
explicative_variables = ['EXT_SOURCE_1', 
                         'EXT_SOURCE_2', 
                         'EXT_SOURCE_3', 
                         'client_installments_AMT_PAYMENT_min_sum',
                         'DAYS_EMPLOYED',
                         'AMT_CREDIT',
                         'DAYS_BIRTH',
                         'previous_CNT_PAYMENT_mean',
                         'bureau_DAYS_CREDIT_max',
                         'client_cash_CNT_INSTALMENT_FUTURE_min_mean']
explicative_data = data.loc[:,explicative_variables]

In [24]:
empty_df = pd.DataFrame(data=None, columns=data.columns, index=[0])

In [25]:
empty_df

,SK_ID_CURR,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,...,ORGANIZATION_TYPE_Bank,ORGANIZATION_TYPE_Business Entity Type 3,ORGANIZATION_TYPE_Construction,ORGANIZATION_TYPE_Military,ORGANIZATION_TYPE_Realtor,ORGANIZATION_TYPE_School,ORGANIZATION_TYPE_Security,ORGANIZATION_TYPE_Self-employed,FONDKAPREMONT_MODE_reg oper account,WALLSMATERIAL_MODE_Panel
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
explicative_data.head()

,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,client_installments_AMT_PAYMENT_min_sum,DAYS_EMPLOYED,AMT_CREDIT,DAYS_BIRTH,previous_CNT_PAYMENT_mean,bureau_DAYS_CREDIT_max,client_cash_CNT_INSTALMENT_FUTURE_min_mean
0,0.752614,0.789654,0.159520,27746.775,-2329.0,568800.0,-19241,8.000000,-49.0,0.0
1,0.564990,0.291656,0.432962,43318.800,-4469.0,222768.0,-18064,12.000000,-62.0,0.0
2,NaN,0.699787,0.610991,66875.266,-4458.0,663264.0,-20038,17.333334,-1210.0,0.0
3,0.525734,0.509677,0.612704,172044.310,-1866.0,1575000.0,-13976,11.333333,-269.0,0.0
4,0.202145,0.425687,NaN,133169.400,-2191.0,625500.0,-13040,24.000000,NaN,0.0

In [9]:
explicative_data.describe()

,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,client_installments_AMT_PAYMENT_min_sum,DAYS_EMPLOYED,AMT_CREDIT,DAYS_BIRTH,previous_CNT_PAYMENT_mean,bureau_DAYS_CREDIT_max,client_cash_CNT_INSTALMENT_FUTURE_min_mean
count,29.000000,49.000000,45.000000,4.700000e+01,43.000000,4.900000e+01,49.000000,47.000000,46.000000,48.000000
mean,0.550443,0.548033,0.467359,4.419494e+05,-2643.790698,5.129940e+05,-15895.959184,15.968672,-420.043478,1.246678
std,0.190442,0.177338,0.185815,7.761405e+05,2511.476217,3.429715e+05,4301.276937,8.241565,427.216622,2.466851
min,0.202145,0.090922,0.159520,1.801800e+02,-13294.000000,4.500000e+04,-23670.000000,3.000000,-1869.000000,0.000000
25%,0.398751,0.394268,0.312365,6.756730e+04,-2922.500000,2.962800e+05,-19241.000000,9.500000,-556.250000,0.000000
50%,0.583118,0.600999,0.474051,1.956917e+05,-2055.000000,4.500000e+05,-15524.000000,15.333333,-300.000000,0.000000
75%,0.696565,0.684407,0.612704,5.426254e+05,-1348.500000,5.688000e+05,-12278.000000,21.055555,-105.500000,1.028214
max,0.866010,0.808788,0.821443,4.861608e+06,-253.000000,1.800000e+06,-8743.000000,42.000000,-17.000000,10.000000

In [10]:
pd.DataFrame(explicative_data.dtypes).to_json(default_handler=str)

'{"0":{"EXT_SOURCE_1":"float64","EXT_SOURCE_2":"float64","EXT_SOURCE_3":"float64","client_installments_AMT_PAYMENT_min_sum":"float64","DAYS_EMPLOYED":"float64","AMT_CREDIT":"float64","DAYS_BIRTH":"int64","previous_CNT_PAYMENT_mean":"float64","bureau_DAYS_CREDIT_max":"float64","client_cash_CNT_INSTALMENT_FUTURE_min_mean":"float64"}}'

In [11]:
SCHEMA_PATH = os.path.join("../..","data","schema","typeAdapters.json")

In [12]:
d = pd.read_json(SCHEMA_PATH, typ='series')

In [13]:
d.iloc[0]

'float'

In [19]:
sample_df = explicative_data.mean().to_frame().T

In [20]:
columns_to_replace = list(sample_df.columns)

In [26]:
empty_df[columns_to_replace] = sample_df

In [28]:
empty_df

,SK_ID_CURR,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,...,ORGANIZATION_TYPE_Bank,ORGANIZATION_TYPE_Business Entity Type 3,ORGANIZATION_TYPE_Construction,ORGANIZATION_TYPE_Military,ORGANIZATION_TYPE_Realtor,ORGANIZATION_TYPE_School,ORGANIZATION_TYPE_Security,ORGANIZATION_TYPE_Self-employed,FONDKAPREMONT_MODE_reg oper account,WALLSMATERIAL_MODE_Panel
0,NaN,NaN,NaN,512994.030612,NaN,-15895.959184,-2643.790698,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
for feature, value in explicative_data.mean().items():
    print(feature, value)

EXT_SOURCE_1 0.5504429448275862
EXT_SOURCE_2 0.5480328559183674
EXT_SOURCE_3 0.4673594288888889
client_installments_AMT_PAYMENT_min_sum 441949.3614255319
DAYS_EMPLOYED -2643.7906976744184
AMT_CREDIT 512994.0306122449
DAYS_BIRTH -15895.959183673469
previous_CNT_PAYMENT_mean 15.968672234042554
bureau_DAYS_CREDIT_max -420.04347826086956
client_cash_CNT_INSTALMENT_FUTURE_min_mean 1.2466779614583332

In [ ]:
a = TypeAdapter(eval("int"))

In [56]:
pd.DataFrame(explicative_data.mean()).reset_index()

                                        index              0
0                                EXT_SOURCE_1       0.550443
1                                EXT_SOURCE_2       0.548033
2                                EXT_SOURCE_3       0.467359
3     client_installments_AMT_PAYMENT_min_sum  441949.361426
4                               DAYS_EMPLOYED   -2643.790698
5                                  AMT_CREDIT  512994.030612
6                                  DAYS_BIRTH  -15895.959184
7                   previous_CNT_PAYMENT_mean      15.968672
8                      bureau_DAYS_CREDIT_max    -420.043478
9  client_cash_CNT_INSTALMENT_FUTURE_min_mean       1.246678

In [61]:
for a, b in pd.DataFrame(explicative_data.mean()).reset_index().to_dict().items():
    print(a,b)

index {0: 'EXT_SOURCE_1', 1: 'EXT_SOURCE_2', 2: 'EXT_SOURCE_3', 3: 'client_installments_AMT_PAYMENT_min_sum', 4: 'DAYS_EMPLOYED', 5: 'AMT_CREDIT', 6: 'DAYS_BIRTH', 7: 'previous_CNT_PAYMENT_mean', 8: 'bureau_DAYS_CREDIT_max', 9: 'client_cash_CNT_INSTALMENT_FUTURE_min_mean'}
0 {0: 0.5504429448275862, 1: 0.5480328559183674, 2: 0.4673594288888889, 3: 441949.3614255319, 4: -2643.7906976744184, 5: 512994.0306122449, 6: -15895.959183673469, 7: 15.968672234042554, 8: -420.04347826086956, 9: 1.2466779614583332}

In [68]:
for a, b in pd.DataFrame(explicative_data.mean()).T.iloc[0,:].items():
    print(a, b)

EXT_SOURCE_1 0.5504429448275862
EXT_SOURCE_2 0.5480328559183674
EXT_SOURCE_3 0.4673594288888889
client_installments_AMT_PAYMENT_min_sum 441949.3614255319
DAYS_EMPLOYED -2643.7906976744184
AMT_CREDIT 512994.0306122449
DAYS_BIRTH -15895.959183673469
previous_CNT_PAYMENT_mean 15.968672234042554
bureau_DAYS_CREDIT_max -420.04347826086956
client_cash_CNT_INSTALMENT_FUTURE_min_mean 1.2466779614583332

In [3]:
training_data = pd.read_csv("..\\..\\data\\original\\training_data.csv")

In [5]:
explicative_training_data = training_data.loc[:,explicative_variables]

In [6]:
explicative_training_data.describe()

,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,client_installments_AMT_PAYMENT_min_sum,DAYS_EMPLOYED,AMT_CREDIT,DAYS_BIRTH,previous_CNT_PAYMENT_mean,bureau_DAYS_CREDIT_max,client_cash_CNT_INSTALMENT_FUTURE_min_mean
count,134133.000000,3.068510e+05,246546.000000,2.916430e+05,252137.000000,3.075110e+05,307511.000000,290642.000000,263491.000000,289420.000000
mean,0.502130,5.143927e-01,0.510853,2.867948e+05,-2384.169325,5.990260e+05,-16036.995067,14.530822,-489.297817,2.071913
std,0.211062,1.910602e-01,0.194844,3.944197e+05,2338.360162,4.024908e+05,4363.988632,8.419878,537.574145,4.334667
min,0.014568,8.173617e-08,0.000527,0.000000e+00,-17912.000000,4.500000e+04,-25229.000000,0.000000,-2922.000000,0.000000
25%,0.334007,3.924574e-01,0.370650,6.173305e+04,-3175.000000,2.700000e+05,-19682.000000,9.000000,-620.000000,0.000000
50%,0.505998,5.659614e-01,0.535276,1.508296e+05,-1648.000000,5.135310e+05,-15750.000000,12.000000,-300.000000,0.000000
75%,0.675053,6.636171e-01,0.669057,3.450571e+05,-767.000000,8.086500e+05,-12413.000000,18.000000,-143.000000,2.000000
max,0.962693,8.549997e-01,0.896010,6.829794e+06,0.000000,4.050000e+06,-7489.000000,72.000000,0.000000,60.000000

In [22]:
explicative_training_data

,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,client_installments_AMT_PAYMENT_min_sum,DAYS_EMPLOYED,AMT_CREDIT,DAYS_BIRTH,previous_CNT_PAYMENT_mean,bureau_DAYS_CREDIT_max,client_cash_CNT_INSTALMENT_FUTURE_min_mean
0,0.083037,0.262949,0.139376,175783.73,-637.0,406597.5,-9461,24.000000,-103.0,6.000000
1,0.311267,0.622246,NaN,1154108.20,-1188.0,1293502.5,-16765,10.000000,-606.0,0.428571
2,NaN,0.555912,0.729567,16071.75,-225.0,135000.0,-19046,4.000000,-408.0,0.000000
3,NaN,0.650442,NaN,994476.70,-3039.0,312682.5,-19005,23.000000,NaN,1.428572
4,NaN,0.322738,NaN,483756.38,-3038.0,513000.0,-19932,20.666666,-1149.0,2.515151
...,...,...,...,...,...,...,...,...,...,...
307506,0.145570,0.681632,NaN,46241.37,-236.0,254700.0,-9327,8.000000,NaN,0.000000
307507,NaN,0.115992,NaN,60281.28,NaN,269550.0,-20775,6.000000,NaN,0.000000
307508,0.744026,0.535722,0.218859,41805.99,-7921.0,677664.0,-14966,5.000000,-713.0,0.000000
307509,NaN,0.514163,0.661024,194556.81,-4786.0,370107.0,-11961,15.000000,-1104.0,5.800000
307510,0.734460,0.708569,0.113922,171612.27,-1262.0,675000.0,-16856,21.750000,-363.0,0.000000

In [15]:
training_data.sample(n=1)["SK_ID_CURR"].item()

167398

In [29]:
profils_list = [
    {
        feature: training_data.sample(n=1)[feature].item()
        for feature in explicative_variables
    } for i in range(3)
]

In [46]:
profils_list[1]

{'EXT_SOURCE_1': nan,
 'EXT_SOURCE_2': 0.5890596,
 'EXT_SOURCE_3': nan,
 'client_installments_AMT_PAYMENT_min_sum': 75878.77,
 'DAYS_EMPLOYED': -809.0,
 'AMT_CREDIT': 178290.0,
 'DAYS_BIRTH': -11118,
 'previous_CNT_PAYMENT_mean': 23.0,
 'bureau_DAYS_CREDIT_max': -317.0,
 'client_cash_CNT_INSTALMENT_FUTURE_min_mean': 0.0}

In [32]:
PROFILS_PATH = "../../data/profils.json"

profils = pd.read_json(PROFILS_PATH, typ='series')

In [41]:
profils[0]['EXT_SOURCE_1'] = float('nan')

In [48]:
type(profils[0]['EXT_SOURCE_1'])

float

In [ ]:
for features in profils[0].keys():
    if profils[0][features]
profils[0]

EXT_SOURCE_1
EXT_SOURCE_2
EXT_SOURCE_3
client_installments_AMT_PAYMENT_min_sum
DAYS_EMPLOYED
AMT_CREDIT
DAYS_BIRTH
previous_CNT_PAYMENT_mean
bureau_DAYS_CREDIT_max
client_cash_CNT_INSTALMENT_FUTURE_min_mean

{'EXT_SOURCE_1': None,
 'EXT_SOURCE_2': 0.21362111,
 'EXT_SOURCE_3': None,
 'client_installments_AMT_PAYMENT_min_sum': 117153.0,
 'DAYS_EMPLOYED': -3080.0,
 'AMT_CREDIT': 808650.0,
 'DAYS_BIRTH': -21157,
 'previous_CNT_PAYMENT_mean': 8.0,
 'bureau_DAYS_CREDIT_max': -130.0,
 'client_cash_CNT_INSTALMENT_FUTURE_min_mean': 19.894737}

In [45]:
random_profil

{'EXT_SOURCE_1': 0.61689305,
 'EXT_SOURCE_2': 0.16040532,
 'EXT_SOURCE_3': 0.25946766,
 'client_installments_AMT_PAYMENT_min_sum': 150665.22,
 'DAYS_EMPLOYED': -7625.0,
 'AMT_CREDIT': 1258650.0,
 'DAYS_BIRTH': -9906,
 'previous_CNT_PAYMENT_mean': 10.0,
 'bureau_DAYS_CREDIT_max': -59.0,
 'client_cash_CNT_INSTALMENT_FUTURE_min_mean': 3.3846154}