In [1]:
import os
import pandas as pd

In [3]:
data = pd.read_csv('../../data/original/demonstration_data.csv', sep = ';')
explicative_variables = ['EXT_SOURCE_1', 
                         'EXT_SOURCE_2', 
                         'EXT_SOURCE_3', 
                         'client_installments_AMT_PAYMENT_min_sum',
                         'DAYS_EMPLOYED',
                         'AMT_CREDIT',
                         'DAYS_BIRTH',
                         'previous_CNT_PAYMENT_mean',
                         'bureau_DAYS_CREDIT_max',
                         'client_cash_CNT_INSTALMENT_FUTURE_min_mean']
explicative_data = data.loc[:,explicative_variables]

In [4]:
explicative_data.head()

,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,client_installments_AMT_PAYMENT_min_sum,DAYS_EMPLOYED,AMT_CREDIT,DAYS_BIRTH,previous_CNT_PAYMENT_mean,bureau_DAYS_CREDIT_max,client_cash_CNT_INSTALMENT_FUTURE_min_mean
0,0.752614,0.789654,0.159520,27746.775,-2329.0,568800.0,-19241,8.000000,-49.0,0.0
1,0.564990,0.291656,0.432962,43318.800,-4469.0,222768.0,-18064,12.000000,-62.0,0.0
2,NaN,0.699787,0.610991,66875.266,-4458.0,663264.0,-20038,17.333334,-1210.0,0.0
3,0.525734,0.509677,0.612704,172044.310,-1866.0,1575000.0,-13976,11.333333,-269.0,0.0
4,0.202145,0.425687,NaN,133169.400,-2191.0,625500.0,-13040,24.000000,NaN,0.0

In [17]:
explicative_data.describe()

,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,client_installments_AMT_PAYMENT_min_sum,DAYS_EMPLOYED,AMT_CREDIT,DAYS_BIRTH,previous_CNT_PAYMENT_mean,bureau_DAYS_CREDIT_max,client_cash_CNT_INSTALMENT_FUTURE_min_mean
count,29.000000,49.000000,45.000000,4.700000e+01,43.000000,4.900000e+01,49.000000,47.000000,46.000000,48.000000
mean,0.550443,0.548033,0.467359,4.419494e+05,-2643.790698,5.129940e+05,-15895.959184,15.968672,-420.043478,1.246678
std,0.190442,0.177338,0.185815,7.761405e+05,2511.476217,3.429715e+05,4301.276937,8.241565,427.216622,2.466851
min,0.202145,0.090922,0.159520,1.801800e+02,-13294.000000,4.500000e+04,-23670.000000,3.000000,-1869.000000,0.000000
25%,0.398751,0.394268,0.312365,6.756730e+04,-2922.500000,2.962800e+05,-19241.000000,9.500000,-556.250000,0.000000
50%,0.583118,0.600999,0.474051,1.956917e+05,-2055.000000,4.500000e+05,-15524.000000,15.333333,-300.000000,0.000000
75%,0.696565,0.684407,0.612704,5.426254e+05,-1348.500000,5.688000e+05,-12278.000000,21.055555,-105.500000,1.028214
max,0.866010,0.808788,0.821443,4.861608e+06,-253.000000,1.800000e+06,-8743.000000,42.000000,-17.000000,10.000000

In [16]:
pd.DataFrame(explicative_data.dtypes).to_json(default_handler=str)

'{"0":{"EXT_SOURCE_1":"float64","EXT_SOURCE_2":"float64","EXT_SOURCE_3":"float64","client_installments_AMT_PAYMENT_min_sum":"float64","DAYS_EMPLOYED":"float64","AMT_CREDIT":"float64","DAYS_BIRTH":"int64","previous_CNT_PAYMENT_mean":"float64","bureau_DAYS_CREDIT_max":"float64","client_cash_CNT_INSTALMENT_FUTURE_min_mean":"float64"}}'

In [25]:
SCHEMA_PATH = os.path.join("../..","data","schema","typeAdapters.json")

In [ ]:
d = pd.read_json(SCHEMA_PATH, typ='series')

In [35]:
d.iloc[0]

'float'

In [48]:
for feature, value in explicative_data.mean().items():
    print(feature, value)

EXT_SOURCE_1 0.5504429448275862
EXT_SOURCE_2 0.5480328559183674
EXT_SOURCE_3 0.4673594288888889
client_installments_AMT_PAYMENT_min_sum 441949.3614255319
DAYS_EMPLOYED -2643.7906976744184
AMT_CREDIT 512994.0306122449
DAYS_BIRTH -15895.959183673469
previous_CNT_PAYMENT_mean 15.968672234042554
bureau_DAYS_CREDIT_max -420.04347826086956
client_cash_CNT_INSTALMENT_FUTURE_min_mean 1.2466779614583332

In [45]:
from pydantic import TypeAdapter, ValidationError

a = TypeAdapter(eval("int"))

In [56]:
pd.DataFrame(explicative_data.mean()).reset_index()

                                        index              0
0                                EXT_SOURCE_1       0.550443
1                                EXT_SOURCE_2       0.548033
2                                EXT_SOURCE_3       0.467359
3     client_installments_AMT_PAYMENT_min_sum  441949.361426
4                               DAYS_EMPLOYED   -2643.790698
5                                  AMT_CREDIT  512994.030612
6                                  DAYS_BIRTH  -15895.959184
7                   previous_CNT_PAYMENT_mean      15.968672
8                      bureau_DAYS_CREDIT_max    -420.043478
9  client_cash_CNT_INSTALMENT_FUTURE_min_mean       1.246678

In [61]:
for a, b in pd.DataFrame(explicative_data.mean()).reset_index().to_dict().items():
    print(a,b)

index {0: 'EXT_SOURCE_1', 1: 'EXT_SOURCE_2', 2: 'EXT_SOURCE_3', 3: 'client_installments_AMT_PAYMENT_min_sum', 4: 'DAYS_EMPLOYED', 5: 'AMT_CREDIT', 6: 'DAYS_BIRTH', 7: 'previous_CNT_PAYMENT_mean', 8: 'bureau_DAYS_CREDIT_max', 9: 'client_cash_CNT_INSTALMENT_FUTURE_min_mean'}
0 {0: 0.5504429448275862, 1: 0.5480328559183674, 2: 0.4673594288888889, 3: 441949.3614255319, 4: -2643.7906976744184, 5: 512994.0306122449, 6: -15895.959183673469, 7: 15.968672234042554, 8: -420.04347826086956, 9: 1.2466779614583332}

In [68]:
for a, b in pd.DataFrame(explicative_data.mean()).T.iloc[0,:].items():
    print(a, b)

EXT_SOURCE_1 0.5504429448275862
EXT_SOURCE_2 0.5480328559183674
EXT_SOURCE_3 0.4673594288888889
client_installments_AMT_PAYMENT_min_sum 441949.3614255319
DAYS_EMPLOYED -2643.7906976744184
AMT_CREDIT 512994.0306122449
DAYS_BIRTH -15895.959183673469
previous_CNT_PAYMENT_mean 15.968672234042554
bureau_DAYS_CREDIT_max -420.04347826086956
client_cash_CNT_INSTALMENT_FUTURE_min_mean 1.2466779614583332

In [71]:
list(explicative_data.mean().index)

['EXT_SOURCE_1',
 'EXT_SOURCE_2',
 'EXT_SOURCE_3',
 'client_installments_AMT_PAYMENT_min_sum',
 'DAYS_EMPLOYED',
 'AMT_CREDIT',
 'DAYS_BIRTH',
 'previous_CNT_PAYMENT_mean',
 'bureau_DAYS_CREDIT_max',
 'client_cash_CNT_INSTALMENT_FUTURE_min_mean']

In [75]:
[list(data.columns) for q in list(explicative_data.mean().index)]

[['SK_ID_CURR',
  'CNT_CHILDREN',
  'AMT_INCOME_TOTAL',
  'AMT_CREDIT',
  'REGION_POPULATION_RELATIVE',
  'DAYS_BIRTH',
  'DAYS_EMPLOYED',
  'DAYS_REGISTRATION',
  'DAYS_ID_PUBLISH',
  'OWN_CAR_AGE',
  'FLAG_WORK_PHONE',
  'REGION_RATING_CLIENT',
  'HOUR_APPR_PROCESS_START',
  'REG_CITY_NOT_LIVE_CITY',
  'EXT_SOURCE_1',
  'EXT_SOURCE_2',
  'EXT_SOURCE_3',
  'APARTMENTS_AVG',
  'BASEMENTAREA_AVG',
  'YEARS_BEGINEXPLUATATION_AVG',
  'YEARS_BUILD_AVG',
  'COMMONAREA_AVG',
  'ENTRANCES_AVG',
  'FLOORSMAX_AVG',
  'LANDAREA_AVG',
  'NONLIVINGAPARTMENTS_AVG',
  'NONLIVINGAREA_AVG',
  'OBS_30_CNT_SOCIAL_CIRCLE',
  'DEF_30_CNT_SOCIAL_CIRCLE',
  'DAYS_LAST_PHONE_CHANGE',
  'FLAG_DOCUMENT_3',
  'FLAG_DOCUMENT_13',
  'FLAG_DOCUMENT_16',
  'FLAG_DOCUMENT_18',
  'AMT_REQ_CREDIT_BUREAU_DAY',
  'AMT_REQ_CREDIT_BUREAU_MON',
  'AMT_REQ_CREDIT_BUREAU_QRT',
  'AMT_REQ_CREDIT_BUREAU_YEAR',
  'bureau_CREDIT_ACTIVE_Sold_mean',
  'bureau_CREDIT_TYPE_Mortgage_mean',
  'bureau_CREDIT_TYPE_Microloan_mean',
  'bureau_CREDIT_TYPE_Car loan_mean',
  'bureau_CREDIT_TYPE_Credit card_mean',
  'bureau_CREDIT_TYPE_Credit card_sum',
  'bureau_CREDIT_ACTIVE_Active_mean',
  'bureau_CREDIT_ACTIVE_Closed_mean',
  'bureau_CREDIT_TYPE_Consumer credit_mean',
  'bureau_CREDIT_ACTIVE_Active_sum',
  'bureau_CREDIT_ACTIVE_Closed_sum',
  'bureau_DAYS_CREDIT_sum',
  'bureau_DAYS_CREDIT_min',
  'bureau_DAYS_CREDIT_ENDDATE_min',
  'bureau_DAYS_CREDIT_UPDATE_min',
  'bureau_DAYS_CREDIT_max',
  'bureau_AMT_CREDIT_SUM_DEBT_min',
  'bureau_AMT_CREDIT_SUM_LIMIT_min',
  'bureau_AMT_ANNUITY_min',
  'bureau_AMT_CREDIT_MAX_OVERDUE_count',
  'bureau_AMT_CREDIT_SUM_LIMIT_mean',
  'bureau_AMT_CREDIT_MAX_OVERDUE_sum',
  'bureau_AMT_ANNUITY_count',
  'bureau_DAYS_CREDIT_ENDDATE_mean',
  'bureau_AMT_ANNUITY_mean',
  'bureau_AMT_CREDIT_SUM_min',
  'bureau_AMT_CREDIT_SUM_mean',
  'client_bureau_balance_MONTHS_BALANCE_sum_sum',
  'client_bureau_balance_STATUS_5_mean_sum',
  'client_bureau_balance_STATUS_2_mean_sum',
  'client_bureau_balance_MONTHS_BALANCE_max_max',
  'client_bureau_balance_STATUS_1_mean_min',
  'client_bureau_balance_STATUS_X_mean_min',
  'client_bureau_balance_STATUS_X_sum_min',
  'client_bureau_balance_STATUS_C_mean_min',
  'client_bureau_balance_STATUS_0_mean_min',
  'client_bureau_balance_STATUS_X_mean_mean',
  'client_bureau_balance_STATUS_C_mean_mean',
  'client_bureau_balance_STATUS_0_sum_min',
  'client_bureau_balance_STATUS_X_mean_sum',
  'client_bureau_balance_STATUS_0_sum_mean',
  'previous_NAME_SELLER_INDUSTRY_MLM partners_mean',
  'previous_NAME_CASH_LOAN_PURPOSE_Journey_mean',
  'previous_NAME_GOODS_CATEGORY_Sport and Leisure_mean',
  'previous_NAME_CASH_LOAN_PURPOSE_Car repairs_mean',
  'previous_NAME_TYPE_SUITE_Group of people_mean',
  'previous_NAME_GOODS_CATEGORY_Other_mean',
  'previous_NAME_CASH_LOAN_PURPOSE_Urgent needs_mean',
  'previous_FLAG_LAST_APPL_PER_CONTRACT_N_mean',
  'previous_CODE_REJECT_REASON_VERIF_mean',
  'previous_CODE_REJECT_REASON_SCOFR_mean',
  'previous_NAME_CASH_LOAN_PURPOSE_Repairs_mean',
  'previous_NAME_SELLER_INDUSTRY_Industry_mean',
  'previous_CHANNEL_TYPE_Channel of corporate sales_mean',
  'previous_NAME_GOODS_CATEGORY_Homewares_mean',
  'previous_NAME_CASH_LOAN_PURPOSE_Other_mean',
  'previous_CODE_REJECT_REASON_SCO_mean',
  'previous_NAME_CONTRACT_STATUS_Unused offer_mean',
  'previous_CODE_REJECT_REASON_HC_mean',
  'previous_NAME_TYPE_SUITE_Other_B_mean',
  'previous_NAME_SELLER_INDUSTRY_Clothing_mean',
  'previous_NAME_TYPE_SUITE_Other_A_mean',
  'previous_NAME_TYPE_SUITE_Children_mean',
  'previous_CHANNEL_TYPE_Contact center_mean',
  'previous_NAME_GOODS_CATEGORY_Computers_mean',
  'previous_NAME_GOODS_CATEGORY_Computers_sum',
  'previous_PRODUCT_COMBINATION_POS industry without interest_mean',
  'previous_NAME_GOODS_CATEGORY_Photo / Cinema Equipment_mean',
  'previous_PRODUCT_COMBINATION_POS household without interest_mean',
  'previous_WEEKDAY_APPR_PROCESS_START_WEDNESDAY_mean',
  'previous_PRODUCT_COMBINATION_POS household without interest_sum',
  'previous_NAME_YIELD_GROUP_low_action_sum',
  'previous_WEEKDAY_APPR_PROCESS_START_WEDNESDAY_sum',
  'previous_CHANNEL_TYPE_AP+ (Cash loan)_mean',
  'previous_NAME_PRODUCT_TYPE_walk-in_mean',
  'previous_WEEKDAY_APPR_PROCESS_START_MONDAY_mean',
  'previous_NAME_PRODUCT_TYPE_walk-in_sum',
  'previous_WEEKDAY_APPR_PROCESS_START_MONDAY_sum',
  'previous_PRODUCT_COMBINATION_Card Street_mean',
  'previous_NAME_SELLER_INDUSTRY_Construction_mean',
  'previous_CODE_REJECT_REASON_LIMIT_mean',
  'previous_PRODUCT_COMBINATION_Card X-Sell_mean',
  'previous_WEEKDAY_APPR_PROCESS_START_TUESDAY_mean',
  'previous_NAME_GOODS_CATEGORY_Audio/Video_mean',
  'previous_WEEKDAY_APPR_PROCESS_START_TUESDAY_sum',
  'previous_PRODUCT_COMBINATION_Cash_mean',
  'previous_WEEKDAY_APPR_PROCESS_START_THURSDAY_mean',
  'previous_WEEKDAY_APPR_PROCESS_START_THURSDAY_sum',
  'previous_PRODUCT_COMBINATION_POS mobile without interest_mean',
  'previous_CHANNEL_TYPE_Regional / Local_mean',
  'previous_NAME_GOODS_CATEGORY_Furniture_mean',
  'previous_NAME_GOODS_CATEGORY_Consumer Electronics_mean',
  'previous_PRODUCT_COMBINATION_POS industry with interest_mean',
  'previous_PRODUCT_COMBINATION_POS household with interest_mean',
  'previous_WEEKDAY_APPR_PROCESS_START_SUNDAY_mean',
  'previous_NAME_PORTFOLIO_Cash_mean',
  'previous_NAME_CLIENT_TYPE_Repeater_mean',
  'previous_NAME_TYPE_SUITE_Unaccompanied_mean',
  'previous_NAME_YIELD_GROUP_middle_mean',
  'previous_NAME_GOODS_CATEGORY_Consumer Electronics_sum',
  'previous_PRODUCT_COMBINATION_POS household with interest_sum',
  'previous_WEEKDAY_APPR_PROCESS_START_SUNDAY_sum',
  'previous_NAME_PORTFOLIO_Cash_sum',
  'previous_NAME_SELLER_INDUSTRY_Auto technology_mean',
  'previous_NAME_CLIENT_TYPE_New_mean',
  'previous_NAME_CLIENT_TYPE_New_sum',
  'previous_CHANNEL_TYPE_Stone_mean',
  'previous_WEEKDAY_APPR_PROCESS_START_SATURDAY_mean',
  'previous_NAME_YIELD_GROUP_low_normal_mean',
  'previous_NAME_PAYMENT_TYPE_XNA_mean',
  'previous_CHANNEL_TYPE_Stone_sum',
  'previous_WEEKDAY_APPR_PROCESS_START_SATURDAY_sum',
  'previous_NAME_YIELD_GROUP_low_normal_sum',
  'previous_PRODUCT_COMBINATION_POS mobile with interest_mean',
  'previous_NAME_YIELD_GROUP_high_mean',
  'previous_NAME_YIELD_GROUP_high_sum',
  'previous_CHANNEL_TYPE_Country-wide_mean',
  'previous_WEEKDAY_APPR_PROCESS_START_FRIDAY_mean',
  'previous_NAME_CLIENT_TYPE_Refreshed_mean',
  'previous_NAME_TYPE_SUITE_Family_mean',
  'previous_NAME_PAYMENT_TYPE_Cash through the bank_mean',
  'previous_CHANNEL_TYPE_Country-wide_sum',
  'previous_WEEKDAY_APPR_PROCESS_START_FRIDAY_sum',
  'previous_NAME_PORTFOLIO_POS_mean',
  'previous_NAME_CONTRACT_STATUS_Approved_mean',
  'previous_NAME_PORTFOLIO_POS_sum',
  'previous_DAYS_DECISION_sum',
  'previous_DAYS_DECISION_min',
  'previous_DAYS_FIRST_DUE_sum',
  'previous_DAYS_FIRST_DUE_min',
  'previous_DAYS_LAST_DUE_sum',
  'previous_DAYS_LAST_DUE_min',
  'previous_DAYS_LAST_DUE_1ST_VERSION_sum',
  'previous_DAYS_LAST_DUE_1ST_VERSION_min',
  'previous_NFLAG_INSURED_ON_APPROVAL_mean',
  'previous_RATE_DOWN_PAYMENT_min',
  'previous_CNT_PAYMENT_min',
  'previous_CNT_PAYMENT_mean',
  'previous_HOUR_APPR_PROCESS_START_min',
  'previous_SELLERPLACE_AREA_min',
  'previous_AMT_DOWN_PAYMENT_min',
  'previous_AMT_ANNUITY_min',
  'previous_AMT_ANNUITY_mean',
  'previous_AMT_CREDIT_min',
  'previous_DAYS_FIRST_DRAWING_min',
  'client_cash_MONTHS_BALANCE_sum_sum',
  'client_cash_MONTHS_BALANCE_sum_max',
  'client_cash_SK_DPD_min_mean',
  'client_cash_SK_DPD_DEF_mean_min',
  'client_cash_SK_DPD_mean_min',
  'client_cash_NAME_CONTRACT_STATUS_Returned to the store_mean_max',
  'client_cash_NAME_CONTRACT_STATUS_Signed_mean_min',
  'client_cash_NAME_CONTRACT_STATUS_Signed_mean_max',
  'client_cash_CNT_INSTALMENT_FUTURE_min_min',
  'client_cash_CNT_INSTALMENT_FUTURE_min_mean',
  'client_cash_NAME_CONTRACT_STATUS_Completed_mean_min',
  'client_cash_NAME_CONTRACT_STATUS_Completed_mean_max',
  'client_cash_NAME_CONTRACT_STATUS_Active_mean_min',
  'client_cash_CNT_INSTALMENT_FUTURE_mean_min',
  'client_cash_SK_DPD_mean_mean',
  'client_cash_NAME_CONTRACT_STATUS_Active_mean_mean',
  'client_cash_NAME_CONTRACT_STATUS_Completed_sum_mean',
  'client_cash_NAME_CONTRACT_STATUS_Active_sum_min',
  'client_cash_NAME_CONTRACT_STATUS_Active_sum_mean',
  'client_credit_MONTHS_BALANCE_sum_sum',
  'client_credit_AMT_RECIVABLE_min_sum',
  'client_credit_CNT_DRAWINGS_POS_CURRENT_min_sum',
  'client_credit_AMT_DRAWINGS_POS_CURRENT_min_sum',
  'client_credit_AMT_PAYMENT_CURRENT_min_sum',
  'client_credit_NAME_CONTRACT_STATUS_Signed_mean_min',
  'client_credit_CNT_DRAWINGS_OTHER_CURRENT_mean_sum',
  'client_credit_AMT_DRAWINGS_OTHER_CURRENT_sum_min',
  'client_credit_CNT_DRAWINGS_POS_CURRENT_sum_min',
  'client_credit_AMT_DRAWINGS_POS_CURRENT_sum_mean',
  'client_credit_AMT_DRAWINGS_POS_CURRENT_max_sum',
  'client_credit_NAME_CONTRACT_STATUS_Completed_mean_min',
  'client_credit_NAME_CONTRACT_STATUS_Completed_sum_min',
  'client_credit_SK_DPD_mean_min',
  'client_credit_CNT_DRAWINGS_ATM_CURRENT_sum_min',
  'client_credit_CNT_INSTALMENT_MATURE_CUM_mean_min',
  'client_credit_AMT_DRAWINGS_CURRENT_mean_min',
  'client_credit_AMT_INST_MIN_REGULARITY_mean_mean',
  'client_credit_AMT_PAYMENT_TOTAL_CURRENT_max_mean',
  'client_credit_NAME_CONTRACT_STATUS_Active_mean_min',
  'client_credit_AMT_CREDIT_LIMIT_ACTUAL_min_min',
  'client_credit_AMT_CREDIT_LIMIT_ACTUAL_min_sum',
  'client_credit_CNT_DRAWINGS_OTHER_CURRENT_mean_mean',
  'client_credit_CNT_DRAWINGS_ATM_CURRENT_mean_min',
  'client_credit_CNT_DRAWINGS_ATM_CURRENT_max_min',
  'client_installments_NUM_INSTALMENT_VERSION_min_max',
  'client_installments_NUM_INSTALMENT_VERSION_mean_mean',
  'client_installments_NUM_INSTALMENT_NUMBER_mean_min',
  'client_installments_AMT_PAYMENT_min_min',
  'client_installments_AMT_PAYMENT_min_max',
  'client_installments_AMT_PAYMENT_min_sum',
  'NAME_CONTRACT_TYPE_Cash loans',
  'CODE_GENDER_F',
  'CODE_GENDER_M',
  'NAME_INCOME_TYPE_State servant',
  'NAME_INCOME_TYPE_Working',
  'NAME_EDUCATION_TYPE_Higher education',
  'NAME_EDUCATION_TYPE_Secondary / secondary special',
  'NAME_FAMILY_STATUS_Civil marriage',
  'NAME_FAMILY_STATUS_Married',
  'NAME_HOUSING_TYPE_House / apartment',
  'NAME_HOUSING_TYPE_Municipal apartment',
  'OCCUPATION_TYPE_Cleaning staff',
  'OCCUPATION_TYPE_Core staff',
  'OCCUPATION_TYPE_Drivers',
  'OCCUPATION_TYPE_High skill tech staff',
  'OCCUPATION_TYPE_Laborers',
  'OCCUPATION_TYPE_Sales staff',
  'WEEKDAY_APPR_PROCESS_START_TUESDAY',
  'WEEKDAY_APPR_PROCESS_START_WEDNESDAY',
  'ORGANIZATION_TYPE_Bank',
  'ORGANIZATION_TYPE_Business Entity Type 3',
  'ORGANIZATION_TYPE_Construction',
  'ORGANIZATION_TYPE_Military',
  'ORGANIZATION_TYPE_Realtor',
  'ORGANIZATION_TYPE_School',
  'ORGANIZATION_TYPE_Security',
  'ORGANIZATION_TYPE_Self-employed',
  'FONDKAPREMONT_MODE_reg oper account',
  'WALLSMATERIAL_MODE_Panel'],
 ['SK_ID_CURR',
  'CNT_CHILDREN',
  'AMT_INCOME_TOTAL',
  'AMT_CREDIT',
  'REGION_POPULATION_RELATIVE',
  'DAYS_BIRTH',
  'DAYS_EMPLOYED',
  'DAYS_REGISTRATION',
  'DAYS_ID_PUBLISH',
  'OWN_CAR_AGE',
  'FLAG_WORK_PHONE',
  'REGION_RATING_CLIENT',
  'HOUR_APPR_PROCESS_START',
  'REG_CITY_NOT_LIVE_CITY',
  'EXT_SOURCE_1',
  'EXT_SOURCE_2',
  'EXT_SOURCE_3',
  'APARTMENTS_AVG',
  'BASEMENTAREA_AVG',
  'YEARS_BEGINEXPLUATATION_AVG',
  'YEARS_BUILD_AVG',
  'COMMONAREA_AVG',
  'ENTRANCES_AVG',
  'FLOORSMAX_AVG',
  'LANDAREA_AVG',
  'NONLIVINGAPARTMENTS_AVG',
  'NONLIVINGAREA_AVG',
  'OBS_30_CNT_SOCIAL_CIRCLE',
  'DEF_30_CNT_SOCIAL_CIRCLE',
  'DAYS_LAST_PHONE_CHANGE',
  'FLAG_DOCUMENT_3',
  'FLAG_DOCUMENT_13',
  'FLAG_DOCUMENT_16',
  'FLAG_DOCUMENT_18',
  'AMT_REQ_CREDIT_BUREAU_DAY',
  'AMT_REQ_CREDIT_BUREAU_MON',
  'AMT_REQ_CREDIT_BUREAU_QRT',
  'AMT_REQ_CREDIT_BUREAU_YEAR',
  'bureau_CREDIT_ACTIVE_Sold_mean',
  'bureau_CREDIT_TYPE_Mortgage_mean',
  'bureau_CREDIT_TYPE_Microloan_mean',
  'bureau_CREDIT_TYPE_Car loan_mean',
  'bureau_CREDIT_TYPE_Credit card_mean',
  'bureau_CREDIT_TYPE_Credit card_sum',
  'bureau_CREDIT_ACTIVE_Active_mean',
  'bureau_CREDIT_ACTIVE_Closed_mean',
  'bureau_CREDIT_TYPE_Consumer credit_mean',
  'bureau_CREDIT_ACTIVE_Active_sum',
  'bureau_CREDIT_ACTIVE_Closed_sum',
  'bureau_DAYS_CREDIT_sum',
  'bureau_DAYS_CREDIT_min',
  'bureau_DAYS_CREDIT_ENDDATE_min',
  'bureau_DAYS_CREDIT_UPDATE_min',
  'bureau_DAYS_CREDIT_max',
  'bureau_AMT_CREDIT_SUM_DEBT_min',
  'bureau_AMT_CREDIT_SUM_LIMIT_min',
  'bureau_AMT_ANNUITY_min',
  'bureau_AMT_CREDIT_MAX_OVERDUE_count',
  'bureau_AMT_CREDIT_SUM_LIMIT_mean',
  'bureau_AMT_CREDIT_MAX_OVERDUE_sum',
  'bureau_AMT_ANNUITY_count',
  'bureau_DAYS_CREDIT_ENDDATE_mean',
  'bureau_AMT_ANNUITY_mean',
  'bureau_AMT_CREDIT_SUM_min',
  'bureau_AMT_CREDIT_SUM_mean',
  'client_bureau_balance_MONTHS_BALANCE_sum_sum',
  'client_bureau_balance_STATUS_5_mean_sum',
  'client_bureau_balance_STATUS_2_mean_sum',
  'client_bureau_balance_MONTHS_BALANCE_max_max',
  'client_bureau_balance_STATUS_1_mean_min',
  'client_bureau_balance_STATUS_X_mean_min',
  'client_bureau_balance_STATUS_X_sum_min',
  'client_bureau_balance_STATUS_C_mean_min',
  'client_bureau_balance_STATUS_0_mean_min',
  'client_bureau_balance_STATUS_X_mean_mean',
  'client_bureau_balance_STATUS_C_mean_mean',
  'client_bureau_balance_STATUS_0_sum_min',
  'client_bureau_balance_STATUS_X_mean_sum',
  'client_bureau_balance_STATUS_0_sum_mean',
  'previous_NAME_SELLER_INDUSTRY_MLM partners_mean',
  'previous_NAME_CASH_LOAN_PURPOSE_Journey_mean',
  'previous_NAME_GOODS_CATEGORY_Sport and Leisure_mean',
  'previous_NAME_CASH_LOAN_PURPOSE_Car repairs_mean',
  'previous_NAME_TYPE_SUITE_Group of people_mean',
  'previous_NAME_GOODS_CATEGORY_Other_mean',
  'previous_NAME_CASH_LOAN_PURPOSE_Urgent needs_mean',
  'previous_FLAG_LAST_APPL_PER_CONTRACT_N_mean',
  'previous_CODE_REJECT_REASON_VERIF_mean',
  'previous_CODE_REJECT_REASON_SCOFR_mean',
  'previous_NAME_CASH_LOAN_PURPOSE_Repairs_mean',
  'previous_NAME_SELLER_INDUSTRY_Industry_mean',
  'previous_CHANNEL_TYPE_Channel of corporate sales_mean',
  'previous_NAME_GOODS_CATEGORY_Homewares_mean',
  'previous_NAME_CASH_LOAN_PURPOSE_Other_mean',
  'previous_CODE_REJECT_REASON_SCO_mean',
  'previous_NAME_CONTRACT_STATUS_Unused offer_mean',
  'previous_CODE_REJECT_REASON_HC_mean',
  'previous_NAME_TYPE_SUITE_Other_B_mean',
  'previous_NAME_SELLER_INDUSTRY_Clothing_mean',
  'previous_NAME_TYPE_SUITE_Other_A_mean',
  'previous_NAME_TYPE_SUITE_Children_mean',
  'previous_CHANNEL_TYPE_Contact center_mean',
  'previous_NAME_GOODS_CATEGORY_Computers_mean',
  'previous_NAME_GOODS_CATEGORY_Computers_sum',
  'previous_PRODUCT_COMBINATION_POS industry without interest_mean',
  'previous_NAME_GOODS_CATEGORY_Photo / Cinema Equipment_mean',
  'previous_PRODUCT_COMBINATION_POS household without interest_mean',
  'previous_WEEKDAY_APPR_PROCESS_START_WEDNESDAY_mean',
  'previous_PRODUCT_COMBINATION_POS household without interest_sum',
  'previous_NAME_YIELD_GROUP_low_action_sum',
  'previous_WEEKDAY_APPR_PROCESS_START_WEDNESDAY_sum',
  'previous_CHANNEL_TYPE_AP+ (Cash loan)_mean',
  'previous_NAME_PRODUCT_TYPE_walk-in_mean',
  'previous_WEEKDAY_APPR_PROCESS_START_MONDAY_mean',
  'previous_NAME_PRODUCT_TYPE_walk-in_sum',
  'previous_WEEKDAY_APPR_PROCESS_START_MONDAY_sum',
  'previous_PRODUCT_COMBINATION_Card Street_mean',
  'previous_NAME_SELLER_INDUSTRY_Construction_mean',
  'previous_CODE_REJECT_REASON_LIMIT_mean',
  'previous_PRODUCT_COMBINATION_Card X-Sell_mean',
  'previous_WEEKDAY_APPR_PROCESS_START_TUESDAY_mean',
  'previous_NAME_GOODS_CATEGORY_Audio/Video_mean',
  'previous_WEEKDAY_APPR_PROCESS_START_TUESDAY_sum',
  'previous_PRODUCT_COMBINATION_Cash_mean',
  'previous_WEEKDAY_APPR_PROCESS_START_THURSDAY_mean',
  'previous_WEEKDAY_APPR_PROCESS_START_THURSDAY_sum',
  'previous_PRODUCT_COMBINATION_POS mobile without interest_mean',
  'previous_CHANNEL_TYPE_Regional / Local_mean',
  'previous_NAME_GOODS_CATEGORY_Furniture_mean',
  'previous_NAME_GOODS_CATEGORY_Consumer Electronics_mean',
  'previous_PRODUCT_COMBINATION_POS industry with interest_mean',
  'previous_PRODUCT_COMBINATION_POS household with interest_mean',
  'previous_WEEKDAY_APPR_PROCESS_START_SUNDAY_mean',
  'previous_NAME_PORTFOLIO_Cash_mean',
  'previous_NAME_CLIENT_TYPE_Repeater_mean',
  'previous_NAME_TYPE_SUITE_Unaccompanied_mean',
  'previous_NAME_YIELD_GROUP_middle_mean',
  'previous_NAME_GOODS_CATEGORY_Consumer Electronics_sum',
  'previous_PRODUCT_COMBINATION_POS household with interest_sum',
  'previous_WEEKDAY_APPR_PROCESS_START_SUNDAY_sum',
  'previous_NAME_PORTFOLIO_Cash_sum',
  'previous_NAME_SELLER_INDUSTRY_Auto technology_mean',
  'previous_NAME_CLIENT_TYPE_New_mean',
  'previous_NAME_CLIENT_TYPE_New_sum',
  'previous_CHANNEL_TYPE_Stone_mean',
  'previous_WEEKDAY_APPR_PROCESS_START_SATURDAY_mean',
  'previous_NAME_YIELD_GROUP_low_normal_mean',
  'previous_NAME_PAYMENT_TYPE_XNA_mean',
  'previous_CHANNEL_TYPE_Stone_sum',
  'previous_WEEKDAY_APPR_PROCESS_START_SATURDAY_sum',
  'previous_NAME_YIELD_GROUP_low_normal_sum',
  'previous_PRODUCT_COMBINATION_POS mobile with interest_mean',
  'previous_NAME_YIELD_GROUP_high_mean',
  'previous_NAME_YIELD_GROUP_high_sum',
  'previous_CHANNEL_TYPE_Country-wide_mean',
  'previous_WEEKDAY_APPR_PROCESS_START_FRIDAY_mean',
  'previous_NAME_CLIENT_TYPE_Refreshed_mean',
  'previous_NAME_TYPE_SUITE_Family_mean',
  'previous_NAME_PAYMENT_TYPE_Cash through the bank_mean',
  'previous_CHANNEL_TYPE_Country-wide_sum',
  'previous_WEEKDAY_APPR_PROCESS_START_FRIDAY_sum',
  'previous_NAME_PORTFOLIO_POS_mean',
  'previous_NAME_CONTRACT_STATUS_Approved_mean',
  'previous_NAME_PORTFOLIO_POS_sum',
  'previous_DAYS_DECISION_sum',
  'previous_DAYS_DECISION_min',
  'previous_DAYS_FIRST_DUE_sum',
  'previous_DAYS_FIRST_DUE_min',
  'previous_DAYS_LAST_DUE_sum',
  'previous_DAYS_LAST_DUE_min',
  'previous_DAYS_LAST_DUE_1ST_VERSION_sum',
  'previous_DAYS_LAST_DUE_1ST_VERSION_min',
  'previous_NFLAG_INSURED_ON_APPROVAL_mean',
  'previous_RATE_DOWN_PAYMENT_min',
  'previous_CNT_PAYMENT_min',
  'previous_CNT_PAYMENT_mean',
  'previous_HOUR_APPR_PROCESS_START_min',
  'previous_SELLERPLACE_AREA_min',
  'previous_AMT_DOWN_PAYMENT_min',
  'previous_AMT_ANNUITY_min',
  'previous_AMT_ANNUITY_mean',
  'previous_AMT_CREDIT_min',
  'previous_DAYS_FIRST_DRAWING_min',
  'client_cash_MONTHS_BALANCE_sum_sum',
  'client_cash_MONTHS_BALANCE_sum_max',
  'client_cash_SK_DPD_min_mean',
  'client_cash_SK_DPD_DEF_mean_min',
  'client_cash_SK_DPD_mean_min',
  'client_cash_NAME_CONTRACT_STATUS_Returned to the store_mean_max',
  'client_cash_NAME_CONTRACT_STATUS_Signed_mean_min',
  'client_cash_NAME_CONTRACT_STATUS_Signed_mean_max',
  'client_cash_CNT_INSTALMENT_FUTURE_min_min',
  'client_cash_CNT_INSTALMENT_FUTURE_min_mean',
  'client_cash_NAME_CONTRACT_STATUS_Completed_mean_min',
  'client_cash_NAME_CONTRACT_STATUS_Completed_mean_max',
  'client_cash_NAME_CONTRACT_STATUS_Active_mean_min',
  'client_cash_CNT_INSTALMENT_FUTURE_mean_min',
  'client_cash_SK_DPD_mean_mean',
  'client_cash_NAME_CONTRACT_STATUS_Active_mean_mean',
  'client_cash_NAME_CONTRACT_STATUS_Completed_sum_mean',
  'client_cash_NAME_CONTRACT_STATUS_Active_sum_min',
  'client_cash_NAME_CONTRACT_STATUS_Active_sum_mean',
  'client_credit_MONTHS_BALANCE_sum_sum',
  'client_credit_AMT_RECIVABLE_min_sum',
  'client_credit_CNT_DRAWINGS_POS_CURRENT_min_sum',
  'client_credit_AMT_DRAWINGS_POS_CURRENT_min_sum',
  'client_credit_AMT_PAYMENT_CURRENT_min_sum',
  'client_credit_NAME_CONTRACT_STATUS_Signed_mean_min',
  'client_credit_CNT_DRAWINGS_OTHER_CURRENT_mean_sum',
  'client_credit_AMT_DRAWINGS_OTHER_CURRENT_sum_min',
  'client_credit_CNT_DRAWINGS_POS_CURRENT_sum_min',
  'client_credit_AMT_DRAWINGS_POS_CURRENT_sum_mean',
  'client_credit_AMT_DRAWINGS_POS_CURRENT_max_sum',
  'client_credit_NAME_CONTRACT_STATUS_Completed_mean_min',
  'client_credit_NAME_CONTRACT_STATUS_Completed_sum_min',
  'client_credit_SK_DPD_mean_min',

In [79]:
pd.DataFrame(columns = [1,2]).empty

True